spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
  properties.hibernate.format_sql: true
  show-sql: true

spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:postgresql://ec2-3-216-4-251.compute-1.amazonaws.com/deh9ll4d9qgk84
  username: ltcplatwppunzm
  password: edbd9c6a1387e3cff0ed95827709ff5bba8a2981fffd2542494ee541c2582c3f
  platform: postgres
  driver-class-name: org.postgresql.Driver

